
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "lg_dates"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.44"
napi = { version = "3.0.0", features = ["chrono_date"] }
napi-derive = "3.0.0"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
